project:
  type: website

website:
  title: "Jeremy's Notes"
  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd

exeucte:
  eval: false


format:
  html:
    theme: darkly
    css: styles.css
    toc: true



